server:
  port: 3000

db:
  type: 'mysql'
  port: 3306
  database: 'CLASSUM_DEV'
  host: '127.0.0.1'
  username: 'root'
  password: 'Larry11physics'
  synchronize: true

jwt:
  secret: 'Secret1234'
  expiresIn: 3600
  refreshSecret: 'Refresh1234'
  refreshExpire: 60 * 60 * 24 * 30

logger:
  level: ['debug']

file:
  limits: